//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUENTAS_POR_PAGAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUE
    {
        public int NUMERO_CHEQUE { get; set; }
        public int NUMERO_FACTURA { get; set; }
        public Nullable<decimal> VALOR_CHEQUE { get; set; }
        public Nullable<System.DateTime> FECHA_CHEQUE { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
    }
}
